// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Auction.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IdChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201407290941241_IdChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
