// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Auction.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UniqueLotName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniqueLotName));
        
        string IMigrationMetadata.Id
        {
            get { return "201407271136317_UniqueLotName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
